#ifndef LOWPOWER_CONF_H
#define LOWPOWER_CONF_H

#define RPL_CONF_LEAF_ONLY 1
#define RESOLV_CONF_SUPPORTS_MDNS 0

#define UIP_CONF_DS6_NBR_NBU     4
#define UIP_CONF_DS6_ROUTE_NBU   0

#define RF_CHANNEL 16

#endif
